import {test,expect} from '@playwright/test';
import {activateTab,openDemo} from './helpers.js';

test.describe('validação dos fluxos recentes',()=>{
 test('matriz, cenários e fechamento aparecem no planejamento da demo',async({page})=>{await openDemo(page);await activateTab(page,'metas');await expect(page.locator('#examMasteryMatrix')).toBeAttached();await expect(page.locator('#weeklyCloseDashboard')).toBeAttached();await expect(page.locator('#gapMapDashboard')).toBeAttached();await expect(page.locator('#postSimulationReplanDashboard')).toBeAttached();await expect(page.locator('#approvalDashboard')).toContainText(/cenário|projeção|disponibilidade/i)});
 test('fechamento e decisões usam linguagem visível ao estudante',async({page})=>{await openDemo(page);await activateTab(page,'metas');await expect(page.locator('#periodComparisonDashboard')).toContainText(/semana anterior/i);await expect(page.locator('#periodComparisonDashboard')).not.toContainText(/accuracy:|minutes:/);await expect(page.locator('#gapMapDashboard')).not.toContainText(/demo-topic-/);await expect(page.locator('#decisionHistoryDashboard')).not.toContainText(/demo-recommendation-/)});
 test('calibração e histórico de decisões preservam estado insuficiente',async({page})=>{await openDemo(page);await activateTab(page,'metas');await expect(page.locator('#recommendationCalibration')).toBeAttached();await expect(page.locator('#decisionHistoryDashboard')).toBeAttached();await expect(page.locator('#recommendationCalibration')).toContainText(/amostra|calibração|recomend/i)});
test('ação de recomendação abre o fluxo especializado',async({page})=>{await openDemo(page);await activateTab(page,'hoje');const recommendation=page.locator('#studyRecommendation'),action=/Iniciar estudo|Iniciar revisão|Resolver questões|Estudar pré-requisito/i;await expect(recommendation).toContainText(action,{timeout:10_000});const start=recommendation.getByRole('button',{name:action}).first();await expect(start).toBeVisible();const label=await start.innerText();await start.click();if(/Resolver questões/i.test(label))await expect(page.locator('#tab-questoes')).toHaveClass(/active/);else if(/revisão/i.test(label))await expect(page.locator('#tab-agenda')).toHaveClass(/active/);else if(/pré-requisito/i.test(label))await expect(page.locator('#tab-disciplinas')).toHaveClass(/active/);else await expect(page.locator('#guidedStrategy')).toBeVisible()});
test('importação repetida permanece idempotente após recarregar',async({page})=>{await page.goto('/');await page.waitForLoadState('networkidle');await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await page.reload();await activateTab(page,'disciplinas');const open=page.locator('#loadDefaultSubjectsBtn');await open.click();await page.getByRole('button',{name:'Continuar'}).click();await page.getByRole('button',{name:'Continuar'}).click();await page.getByRole('button',{name:'Importar',exact:true}).click();const subjects=await page.locator('.subject-block').count();await expect.poll(()=>page.evaluate(()=>localStorage.length)).toBeGreaterThan(0);await page.reload();await activateTab(page,'disciplinas');await open.click();await page.getByRole('button',{name:'Continuar'}).click();await page.getByRole('button',{name:'Continuar'}).click();expect(await page.locator('.subject-block').count()).toBe(subjects);if(await page.getByRole('button',{name:'Importar',exact:true}).isEnabled())await page.getByRole('button',{name:'Importar',exact:true}).click();expect(await page.locator('.subject-block').count()).toBe(subjects)});
 test('modo móvel mantém os painéis recentes sem overflow',async({page})=>{await page.setViewportSize({width:375,height:812});await openDemo(page);await activateTab(page,'metas');const dimensions=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth}));expect(dimensions.width).toBeLessThanOrEqual(dimensions.viewport);await expect(page.locator('#examMasteryMatrix')).toBeVisible()});
});


