import {test,expect} from '@playwright/test';
import {activateTab,openDemo} from './helpers.js';

test.describe('validação dos fluxos recentes',()=>{
 test('matriz, cenários e fechamento aparecem no planejamento da demo',async({page})=>{await openDemo(page);await activateTab(page,'metas');await expect(page.locator('#examMasteryMatrix')).toBeAttached();await expect(page.locator('#weeklyCloseDashboard')).toBeAttached();await expect(page.locator('#gapMapDashboard')).toBeAttached();await expect(page.locator('#postSimulationReplanDashboard')).toBeAttached();await expect(page.locator('#approvalDashboard')).toContainText(/cenário|projeção|disponibilidade/i)});
 test('calibração e histórico de decisões preservam estado insuficiente',async({page})=>{await openDemo(page);await activateTab(page,'metas');await expect(page.locator('#recommendationCalibration')).toBeAttached();await expect(page.locator('#decisionHistoryDashboard')).toBeAttached();await expect(page.locator('#recommendationCalibration')).toContainText(/amostra|calibração|recomend/i)});
 test('estudo guiado exibe estratégia ao iniciar uma recomendação',async({page})=>{await openDemo(page);await activateTab(page,'hoje');const start=page.getByRole('button',{name:/Iniciar estudo/i}).first();await expect(start).toBeVisible();await start.click();await expect(page.locator('#guidedStrategy')).toBeVisible();await expect(page.locator('#guidedStrategy')).toContainText(/etapa|estratégia/i)});
 test('importação repetida permanece idempotente após recarregar',async({page})=>{await page.goto('/');await page.evaluate(()=>{localStorage.clear();sessionStorage.clear()});await page.reload();await activateTab(page,'disciplinas');const open=page.getByRole('button',{name:/Carregar disciplinas do edital/i});await open.click();await page.getByRole('button',{name:'Continuar'}).click();await page.getByRole('button',{name:'Continuar'}).click();await page.getByRole('button',{name:'Importar',exact:true}).click();const subjects=await page.locator('.subject-block').count();await page.reload();await activateTab(page,'disciplinas');await open.click();await page.getByRole('button',{name:'Continuar'}).click();await page.getByRole('button',{name:'Continuar'}).click();await expect(page.getByRole('button',{name:'Importar',exact:true})).toBeDisabled();expect(await page.locator('.subject-block').count()).toBe(subjects)});
 test('modo móvel mantém os painéis recentes sem overflow',async({page})=>{await page.setViewportSize({width:375,height:812});await openDemo(page);await activateTab(page,'metas');const dimensions=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth}));expect(dimensions.width).toBeLessThanOrEqual(dimensions.viewport);await expect(page.locator('#examMasteryMatrix')).toBeVisible()});
});
