export const WEEKLY_CLOSE_VERSION='2.0.0';
const n=value=>Number.isFinite(Number(value))?Number(value):0;
const pct=(a,b)=>b>0?Math.round(a/b*100):null;
const comparison=(current,previous,unit)=>{if(previous==null)return{current,previous:null,delta:null,direction:'insufficient',unit};const delta=Math.round((current-previous)*10)/10;return{current,previous,delta,direction:delta>0?'up':delta<0?'down':'stable',unit}};
export function buildWeeklyClose({period,current={},previous={},sessions=[],plans=[],questions=[],recommendations=[],targetAccuracy=80}={}){
 const planned=n(current.plannedMinutes),executed=n(current.executedMinutes),plannedCount=plans.length,completedCount=plans.filter(x=>['completed','done','Concluído'].includes(x.status)).length;
 const resolved=questions.reduce((s,q)=>s+n(q.resolved),0),correct=questions.reduce((s,q)=>s+n(q.correct),0);
 const adherence=planned>0?Math.round(executed/planned*100):null;
 const state=planned||executed||resolved?'available':'insufficient';
 const accuracy=resolved?pct(correct,resolved):null,previousAccuracy=Number.isFinite(Number(previous.accuracy))?Number(previous.accuracy):null,previousMinutes=Number.isFinite(Number(previous.executedMinutes??previous.minutes))?Number(previous.executedMinutes??previous.minutes):null,previousResolved=Number.isFinite(Number(previous.resolved))?Number(previous.resolved):null;
 const comparisons={accuracy:accuracy==null?{current:null,previous:previousAccuracy,delta:null,direction:'insufficient',unit:'percentage_points'}:comparison(accuracy,previousAccuracy,'percentage_points'),minutes:comparison(executed,previousMinutes,'minutes'),questions:comparison(resolved,previousResolved,'count')};
 const accuracyGap=accuracy==null?null:Math.round((accuracy-targetAccuracy)*10)/10,bestSignal=comparisons.accuracy.delta>0?{type:'accuracy',message:`O acerto avançou ${comparisons.accuracy.delta} p.p.`}:comparisons.minutes.delta>0?{type:'minutes',message:'O tempo de estudo aumentou.'}:resolved>0?{type:'questions',message:`Você resolveu ${resolved} questões.`}:null;
 const mainRisk=accuracyGap!=null&&accuracyGap<0?{type:'accuracy_below_target',message:`O acerto ficou ${Math.abs(accuracyGap)} p.p. abaixo da meta de ${targetAccuracy}%.`}:planned>executed?{type:'execution_deficit',message:`Faltaram ${planned-executed} min para executar o planejado.`}:null;
 const recommendedAction=mainRisk?.type==='accuracy_below_target'?'Priorizar questões e revisão dos tópicos com maior lacuna.':mainRisk?.type==='execution_deficit'?'Readequar a carga da próxima semana à capacidade disponível.':'Manter o plano e consolidar os tópicos com revisão espaçada.';
 return{algorithmVersion:WEEKLY_CLOSE_VERSION,period,state,investment:{plannedMinutes:planned,executedMinutes:executed,deficitMinutes:Math.max(0,planned-executed),adherence},execution:{plannedItems:plannedCount,completedItems:completedCount,rate:plannedCount?pct(completedCount,plannedCount):null},questions:{resolved,correct,accuracy},recommendations:{total:recommendations.length,accepted:recommendations.filter(x=>x.accepted||x.status==='accepted').length},comparison:comparisons,assessment:accuracyGap==null?'insufficient':accuracyGap>=0?'on_target':'attention',bestSignal,mainRisk,recommendedAction,priorities:[],reasons:state==='insufficient'?['Registre sessões, planos ou questões para fechar a semana.']:[]};
}
