const sum=(items,selector)=>items.reduce((total,item)=>total+(Number(selector(item))||0),0);
const shiftDate=(iso,days)=>{const [year,month,day]=iso.split('-').map(Number),date=new Date(Date.UTC(year,month-1,day+days));return date.toISOString().slice(0,10)};
const inPeriod=(item,start,end)=>{const date=item.date||String(item.endedAt||item.createdAt||'').slice(0,10);return Boolean(date&&date>=start&&date<=end)};
export function resolveReportPeriod({preset='30',start=null,end=null,generatedAt}={}){const today=String(generatedAt||new Date().toISOString()).slice(0,10);if(preset==='custom'&&start&&end&&start<=end)return{preset,start,end,label:`${start} a ${end}`};const days=Math.max(1,Number(preset)||30);return{preset:String(days),start:shiftDate(today,-(days-1)),end:today,label:`Últimos ${days} dias`}}
export function buildStrategicReport({state,generatedAt,isDemo=false,readiness=null,diagnosis=null,forecast=null,period}={}){
  const range=resolveReportPeriod({...period,generatedAt}),subjects=(state.subjects||[]).filter(item=>!item.archived),topics=subjects.flatMap(subject=>(subject.topics||[]).filter(item=>!item.archived));
  const sessions=(state.studySessions||[]).filter(item=>inPeriod(item,range.start,range.end)),questions=(state.questoes||[]).filter(item=>inPeriod(item,range.start,range.end)),simulations=(state.simulados||[]).filter(item=>inPeriod(item,range.start,range.end)),reviews=(state.reviewAgenda||[]).filter(item=>inPeriod(item,range.start,range.end));
  const resolved=sum(questions,item=>item.resolved),correct=sum(questions,item=>item.correct),studySeconds=sum(sessions,item=>item.durationSeconds),simulationTotal=sum(simulations,item=>item.total),simulationCorrect=sum(simulations,item=>item.correct),activePlan=[...(state.studyPlans||[])].reverse().find(item=>!item.undoneAt)||null,adjustments=(state.planAdjustments||[]).filter(item=>inPeriod(item,range.start,range.end)),feedback=(state.recommendationFeedback||[]).filter(item=>inPeriod(item,range.start,range.end));
  const bySubject=subjects.map(subject=>{const subjectSessions=sessions.filter(item=>item.subjectId===subject.id),subjectQuestions=questions.filter(item=>item.subjectId===subject.id),volume=sum(subjectQuestions,item=>item.resolved),hits=sum(subjectQuestions,item=>item.correct);return{id:subject.id,name:subject.name,studySeconds:sum(subjectSessions,item=>item.durationSeconds),questions:volume,accuracy:volume?Math.round(hits/volume*100):null,completed:(subject.topics||[]).filter(item=>!item.archived&&item.status==='Concluído').length,total:(subject.topics||[]).filter(item=>!item.archived).length}}).sort((a,b)=>b.studySeconds-a.studySeconds),planned=sum(state.dailyPlans||[],plan=>inPeriod(plan,range.start,range.end)?sum(plan.items||[],item=>item.plannedMinutes):0),executed=Math.round(studySeconds/60);
  return {title:isDemo?'Relatório estratégico de demonstração':'Relatório estratégico',isDemo,generatedAt,period:range,exam:{date:state.examDate||state.examBlueprint?.examDate||null,target:state.examBlueprint?.targetScore??state.metas?.metaAprovacao??null},overview:{subjects:subjects.length,topics:topics.length,completedTopics:topics.filter(item=>item.status==='Concluído').length,studySeconds,resolved,accuracy:resolved?Math.round(correct/resolved*100):null,simulations:simulations.length,simulationAverage:simulationTotal?Math.round(simulationCorrect/simulationTotal*100):null,pendingReviews:reviews.filter(item=>item.status!=='Concluído').length,completedReviews:reviews.filter(item=>item.status==='Concluído').length},readiness,forecast,activePlan,bySubject,simulations:simulations.map(item=>({date:item.date,name:item.nome||'Simulado',score:item.total?Math.round(item.correct/item.total*100):null})),execution:{plannedMinutes:planned,executedMinutes:executed,adherence:planned?Math.round(executed/planned*100):null,dailyPlans:(state.dailyPlans||[]).filter(item=>inPeriod(item,range.start,range.end)).length,replans:adjustments.filter(item=>['applied','confirmed'].includes(item.status)).length,undoneReplans:adjustments.filter(item=>item.status==='undone').length},risks:(diagnosis?.bottlenecks||[]).slice(0,5),opportunities:(diagnosis?.opportunities||[]).slice(0,5),priorities:[...(diagnosis?.bottlenecks||[]),...(diagnosis?.opportunities||[])].slice(0,5),recommendations:{decisions:feedback.length,accepted:feedback.filter(item=>item.accepted).length,completed:feedback.filter(item=>item.completed).length,useful:feedback.filter(item=>item.useful===true).length,measured:feedback.filter(item=>item.outcome).length},errors:Object.entries(questions.reduce((totals,item)=>{Object.entries(item.errorBreakdown||{}).forEach(([key,value])=>totals[key]=(totals[key]||0)+(Number(value)||0));return totals},{})).sort((a,b)=>b[1]-a[1])};
}
