export const CATALOG_VERSION='2.0.0';
export const EXAM_TAGS=Object.freeze({BB:'bb-escriturario',CAIXA:'caixa-tbn',CAIXA_TI:'caixa-tbn-ti'});
const {BB,CAIXA,CAIXA_TI}=EXAM_TAGS;
const common=[BB,CAIXA,CAIXA_TI],caixa=[CAIXA,CAIXA_TI];
const slug=value=>String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const topic=(name,examTags=common,extra={})=>Object.freeze({id:extra.id||slug(name),catalogId:extra.id||slug(name),name,examTags:[...examTags],institutions:[...new Set(examTags.map(tag=>tag.startsWith('bb')?'bb':'caixa'))],aliases:extra.aliases||[],sourceRefs:extra.sourceRefs||examTags.map(tag=>tag==='bb-escriturario'?'bb-2023':tag)});
const subject=(id,name,names,{aliases=[],defaultTags=common}={})=>Object.freeze({id,catalogId:id,name,aliases,topics:names.map(item=>Array.isArray(item)?topic(item[0],item[1]||defaultTags,item[2]||{}):topic(item,defaultTags))});
export const EXAM_CATALOG=Object.freeze([
 subject('lingua-portuguesa','Língua Portuguesa',['Compreensão e interpretação de textos','Tipologia e gêneros textuais','Ortografia oficial','Acentuação gráfica','Classes de palavras','Sintaxe da oração e do período','Concordância nominal e verbal','Regência nominal e verbal','Crase','Pontuação','Coesão e coerência','Significação das palavras','Redação oficial'],{aliases:['Português']}),
 subject('lingua-inglesa','Língua Inglesa',[['Compreensão de textos em língua inglesa',[CAIXA_TI]],['Vocabulário e aspectos gramaticais',[CAIXA_TI]]],{defaultTags:[CAIXA_TI]}),
 subject('matematica','Matemática',[['Números inteiros e racionais',[BB]],['Razão e proporção',[BB]],['Regra de três simples e composta',[BB]],['Porcentagem',[BB]],['Equações e sistemas',[BB]],['Funções',[BB]],['Progressões aritméticas e geométricas',[BB]],['Geometria plana e espacial',[BB]],['Análise combinatória',[BB]],['Probabilidade básica',[BB]]]),
 subject('matematica-financeira','Matemática Financeira',['Conceitos gerais e valor do dinheiro no tempo','Juros simples','Juros compostos','Taxas nominal, efetiva e equivalente','Descontos simples e compostos','Séries uniformes','Sistemas de amortização','Fluxo de caixa','Valor presente e valor futuro']),
 subject('probabilidade-estatistica','Probabilidade e Estatística',[['Estatística descritiva',caixa],['Medidas de posição e dispersão',caixa],['Distribuições de probabilidade',caixa],['Probabilidade condicional',caixa],['Variáveis aleatórias',caixa],['Amostragem e estimação',caixa],['Correlação e regressão',caixa]],{defaultTags:caixa}),
 subject('conhecimentos-bancarios','Conhecimentos Bancários',['Sistema Financeiro Nacional','Conselho Monetário Nacional','Banco Central do Brasil','Comissão de Valores Mobiliários','Instituições financeiras','Mercado monetário','Mercado de crédito','Mercado de capitais','Mercado de câmbio','Política monetária','Taxa Selic','Inflação e índices de preços','Garantias do Sistema Financeiro Nacional']),
 subject('produtos-servicos-bancarios','Produtos e Serviços Bancários',['Contas correntes e depósitos','Cartões de crédito e débito','Crédito direto ao consumidor','Crédito rural','Financiamento habitacional','Capitalização','Previdência privada','Seguros','Consórcios','Investimentos e fundos','Títulos de renda fixa','PIX','Open Finance','Correspondentes bancários']),
 subject('mercado-transformacao','Mercado Financeiro e Transformação Digital',['Fintechs e bancos digitais','Startups e big techs','Moedas digitais e criptomoedas','Blockchain','Marketplace','Banking as a Service','Sistemas de pagamentos instantâneos','Transformação digital no sistema financeiro','Novos modelos de negócio','Experiência digital do cliente']),
 subject('vendas-negociacao','Vendas e Negociação',[['Noções de estratégia empresarial',[BB]],['Segmentação de mercado',[BB]],['Gestão da experiência do cliente',[BB]],['Técnicas de vendas',[BB]],['Técnicas de negociação',[BB]],['Marketing digital',[BB]],['Ética em vendas',[BB]],['Padrões de qualidade no atendimento',[BB]],['Comportamento do consumidor',[BB]]]),
 subject('atendimento-bancario','Atendimento Bancário',['Atendimento e relacionamento com o cliente','Código de Defesa do Consumidor','Ouvidoria','Atendimento prioritário','Acessibilidade e inclusão','Qualidade em serviços','Resolução de conflitos','Comunicação assertiva']),
 subject('informatica-tic','Informática e TIC',['Sistemas operacionais','Pacote Microsoft Office','Internet e intranet','Navegadores e correio eletrônico','Redes de computadores','Segurança da informação','Computação em nuvem','Ferramentas de colaboração','Proteção de estações de trabalho'],{aliases:['Informática']}),
 subject('tecnologia-ia','Tecnologia e Inteligência Artificial',[['Lógica de programação',[CAIXA_TI]],['Algoritmos e estruturas de dados',[CAIXA_TI]],['Programação Java',[CAIXA_TI]],['Programação Python',[CAIXA_TI]],['Bancos de dados relacionais',[CAIXA_TI]],['Bancos de dados NoSQL',[CAIXA_TI]],['Engenharia de software',[CAIXA_TI]],['Arquitetura de software',[CAIXA_TI]],['APIs e microsserviços',[CAIXA_TI]],['DevOps e DevSecOps',[CAIXA_TI]],['Contêineres e orquestração',[CAIXA_TI]],['Testes de software',[CAIXA_TI]],['Métodos ágeis',[CAIXA_TI]],['Ciência de dados',[CAIXA_TI]],['Aprendizado de máquina',[CAIXA_TI]],['Inteligência artificial generativa',[CAIXA_TI]],['Governança de TI',[CAIXA_TI]],['Segurança cibernética',[CAIXA_TI]]],{defaultTags:[CAIXA_TI],aliases:['Tecnologia da Informação','TI']}),
 subject('compliance-etica','Compliance, Ética e Legislação Bancária',['Prevenção à lavagem de dinheiro','Financiamento ao terrorismo','Lei Anticorrupção','Lei Geral de Proteção de Dados','Sigilo bancário','Ética profissional','Governança corporativa','Responsabilidade socioambiental','Controles internos','Gestão de riscos','Segurança cibernética no setor bancário']),
 subject('comportamentos-digitais','Conhecimentos e Comportamentos Digitais',[['Growth mindset',caixa],['Intraempreendedorismo',caixa],['Design Thinking',caixa],['Scrum',caixa],['Resolução de problemas complexos',caixa],['Liderança e autoliderança',caixa],['Inteligência emocional',caixa],['Objetivos de Desenvolvimento Sustentável',caixa],['OKR',caixa],['Produtividade pessoal',caixa],['Trabalho remoto e colaboração',caixa],['Lifelong learning',caixa]],{defaultTags:caixa}),
 subject('caixa-especificos','Caixa Econômica Federal — Específicos',[['FGTS',[CAIXA],{sourceRefs:[]}],['Seguro-desemprego',[CAIXA],{sourceRefs:[]}],['Abono salarial',[CAIXA],{sourceRefs:[]}],['PIS',[CAIXA],{sourceRefs:[]}],['Programas sociais',[CAIXA],{sourceRefs:[]}],['Financiamento habitacional da Caixa',[CAIXA],{sourceRefs:[]}]],{defaultTags:[CAIXA]}),
 subject('bb-especificos','Banco do Brasil — Específicos',[['Código de Ética do Banco do Brasil',[BB]],['Estratégia corporativa do Banco do Brasil',[BB]],['Políticas de responsabilidade socioambiental do BB',[BB]],['Estrutura e atuação do Banco do Brasil',[BB]]],{defaultTags:[BB]}),
 subject('redacao','Redação',[['Estrutura do texto dissertativo-argumentativo',[BB]],['Tema, tese e argumentação',[BB]],['Coesão e coerência na redação',[BB]],['Norma-padrão aplicada à redação',[BB]],['Proposta de intervenção',[BB]]],{defaultTags:[BB]})
]);
export function catalogForExamTags(examTags=[]){const selected=new Set(examTags);return EXAM_CATALOG.map(group=>({...group,topics:group.topics.filter(item=>item.examTags.some(tag=>selected.has(tag)))})).filter(group=>group.topics.length)}
