export const HELP_CATEGORIES=[
  {id:'guide-start',title:'Comece por aqui',summary:'Da prova ao primeiro fechamento semanal, um passo de cada vez.',entries:[
    {id:'first-steps',title:'Primeiros passos',summary:'O caminho básico para começar a receber orientações úteis.',steps:[{title:'Configure sua prova',detail:'Escolha o concurso, a data e as informações estratégicas.'},{title:'Monte o edital',detail:'Cadastre ou importe disciplinas e tópicos.'},{title:'Defina sua disponibilidade',detail:'Informe o tempo que você realmente pode estudar.'},{title:'Registre seus estudos',detail:'Vincule sessões aos tópicos sempre que possível.'},{title:'Resolva questões e faça revisões',detail:'O desempenho e a manutenção do conhecimento ganham contexto.'},{title:'Acompanhe o diagnóstico',detail:'Veja riscos, lacunas e a força das evidências.'},{title:'Siga as recomendações',detail:'Escolha a próxima ação com base na prova e no seu progresso.'},{title:'Faça o fechamento semanal',detail:'Compare o plano com o que foi executado.'}],paragraphs:['Você não precisa configurar tudo de uma vez. Comece pela prova, pelo conteúdo e pela disponibilidade. Conforme registra sessões, questões e revisões, o StudyTrack personaliza as análises.'],action:{label:'Abrir Disciplinas',target:'subjects'}},
    {id:'overview',title:'Visão Geral',summary:'Seu painel principal de acompanhamento.',paragraphs:['Reúne Índice de Prontidão, progresso, foco da semana, recomendações, evolução, riscos, oportunidades e conquistas. O índice resume sinais da preparação; não é probabilidade de aprovação.'],action:{label:'Abrir Visão Geral',target:'overview'}}
  ]},
  {id:'guide-areas',title:'Estudar',summary:'Disciplinas, sessões, Questões e Simulados, revisões e próxima ação.',entries:[
    {id:'today-guide',title:'Hoje',summary:'A próxima ação e o plano do dia em um só lugar.',paragraphs:['O card Hoje na Visão Geral mostra o tempo planejado, o estudo realizado e a próxima atividade. Inicie pelo card para vincular a sessão à tarefa. O progresso considera disciplina, tópico e tipo: teoria não conclui uma tarefa de questões. Estudo sem vínculo aparece como adicional.','Após registrar, editar ou excluir uma sessão, o progresso é atualizado. Uma recomendação fora do plano deve ser revisada antes de mudar a carga. Após Recovery, confira atividades geradas por uma versão anterior do plano. Pendências ficam disponíveis na aba Hoje, sem fechamento diário obrigatório.'],action:{label:'Abrir Hoje',target:'today'}},
    {id:'subjects',title:'Disciplinas e tópicos',summary:'A estrutura que conecta conteúdo e desempenho.',paragraphs:['Cada disciplina reúne tópicos. Sessões, questões, revisões, domínio e histórico ficam associados ao tópico quando você o informa. Cadastre manualmente ou importe um edital; conteúdos compartilhados entre concursos podem reutilizar o progresso.'],bullets:['Tags identificam em quais concursos cada tópico aparece.','O concurso ativo define o escopo padrão das análises.','Registros apenas da disciplina permanecem no histórico, mas não são atribuídos automaticamente a um edital específico.'],action:{label:'Cadastrar conteúdo',target:'subjects'}},
    {id:'calendar-guide',title:'Calendário',summary:'Enxergue a carga de estudo por data.',paragraphs:['O calendário reúne sessões, revisões e atividades planejadas. Use seus filtros para investigar períodos e disciplinas antes de redistribuir a semana.'],action:{label:'Abrir Calendário',target:'calendar'}},
    {id:'sessions',title:'Cronômetro e sessões',summary:'Registre o estudo real, com ou sem cronômetro.',paragraphs:['Escolha disciplina, tópico e tipo de estudo, registre a duração e finalize a sessão. Também é possível lançar uma sessão manual e vincular resultados posteriores. Prefira informar o tópico: isso melhora a precisão do domínio, das prioridades e do impacto da prova.'],action:{label:'Abrir cronômetro',target:'timer'}},
    {id:'questions',title:'Questões e Simulados',summary:'Desempenho e análise de erros têm registro próprio.',paragraphs:['Informe quantidade de questões, acertos, tópico e, quando possível, a causa dos erros. Os simulados mostram desempenho por disciplina e podem fundamentar uma proposta de replanejamento.'],bullets:['Não sabia · Esqueci','Interpretação · Cálculo','Desatenção · Chute'],note:'Categorizar erros ajuda a distinguir falta de conhecimento de problemas de execução.',action:{label:'Registrar questões',target:'questions'}},
    {id:'reviews',title:'Revisões',summary:'Acompanhe o que está próximo e o que já atrasou.',paragraphs:['A Agenda separa revisões atrasadas, de hoje e próximas. A saúde das revisões ajuda a sinalizar manutenção do conhecimento; concluir uma revisão registra a execução real. Uma revisão crítica merece atenção, mas não deve ser tratada apenas como checklist.'],action:{label:'Abrir Agenda de Revisões',target:'reviews'}},
    {id:'recommendations',title:'Recomendações inteligentes',summary:'O que importa na prova + sua necessidade → próxima ação.',flow:['Prova: impacto e evidência','Você: domínio, retenção e tendência','Ação: estudar, revisar ou resolver questões'],paragraphs:['A prioridade considera impacto na prova, domínio, retenção, tendência, revisões, desempenho, evidência disponível e pré-requisitos. Sempre que há dados suficientes, o StudyTrack mostra os fatores que levaram à sugestão. Uma recomendação pode iniciar uma sessão vinculada à decisão.'],action:{label:'Ver próxima ação',target:'today'}}
  ]},
  {id:'guide-workflows',title:'Planejar',summary:'Capacidade semanal, planejamento adaptativo e fechamento.',entries:[
    {id:'planning',title:'Planejar a semana',summary:'Compare disponibilidade, proposta e execução.',paragraphs:['Defina as horas disponíveis, gere uma proposta semanal e confira a distribuição por disciplina, tópico e atividade. O plano até a prova considera capacidade e pendências. Confirme antes de salvar; déficit e excedente indicam quando a carga não cabe.'],action:{label:'Abrir planejamento',target:'planning'}},
    {id:'adaptive',title:'Planejamento Adaptativo',summary:'Redistribuir tempo sem criar horas adicionais.',flow:['Impacto na prova','Necessidade do estudante','Possível redistribuição'],paragraphs:['Quando uma disciplina está consolidada e outra apresenta necessidade estratégica maior, o StudyTrack pode propor uma transferência limitada de minutos. A capacidade semanal é preservada. A prévia explica o motivo e exige confirmação; um intervalo de proteção evita ajustes repetidos em pouco tempo.'],action:{label:'Ver planejamento adaptativo',target:'planning'}},
    {id:'weekly',title:'Fechamento semanal',summary:'Entenda o que foi planejado, executado e medido.',paragraphs:['O fechamento reúne tempo, questões, acerto, lacunas, diagnóstico e próxima ação. O foco estratégico indica a parcela do tempo dedicada a tópicos de alto impacto; não é uma meta de 100%. Melhora ou estabilidade só aparece quando há resultado posterior medido no período.'],bullets:['Salve o fechamento para comparar semanas do mesmo concurso.','A comparação exige períodos sem sobreposição e dados completos.','O foco pode subir enquanto o tempo executado cai; leia os dois sinais juntos.'],action:{label:'Ver Fechamento Semanal',target:'weekly'}}
  ]},
  {id:'guide-data',title:'Analisar',summary:'Diagnóstico, prontidão, conquistas e resultados posteriores.',entries:[
    {id:'adherence',title:'Execução e aderência',summary:'Entenda a diferença entre acumular horas e executar as prioridades do plano.',paragraphs:['Em Desempenho → Consistência, volume compara horas realizadas e previstas e pode superar 100%. Aderência ao plano usa apenas tempo com vínculo seguro e atividade compatível, limitado à duração prevista. Execução prioritária usa a prioridade registrada quando o planejamento foi criado.','O histórico de 4, 8 ou 12 semanas compara a semana em andamento com os mesmos dias da anterior. Pouca classificação histórica deixa a interpretação estratégica indisponível.','Em Metas, você pode definir uma meta pessoal de aderência entre 50 e 100% ou desativá-la. Consistência e Trajetória mostram o crédito da semana até hoje; a meta não altera Prontidão, prioridade ou projeção. Ao salvar um fechamento, os valores e as explicações ficam preservados. Pendências recorrentes usam períodos salvos sem sobreposição no mesmo concurso. Revisar planejamento abre Metas; qualquer alteração exige prévia e confirmação.'],action:{label:'Ver execução e aderência',target:'adherence'}},
    {id:'diagnosis',title:'Central de Diagnóstico',summary:'Riscos, lacunas, oportunidades e qualidade das evidências.',paragraphs:['Domínio resume o desempenho observado; retenção indica manutenção do conhecimento; tendência aponta a direção recente; evidência mostra o quanto a conclusão é sustentada. Impacto representa importância na prova, e lacuna combina essa importância com a necessidade pessoal.'],action:{label:'Abrir diagnóstico',target:'diagnosis'}},
    {id:'readiness',title:'Índice de Prontidão',summary:'Uma síntese de 0 a 100, sempre acompanhada de confiança.',paragraphs:['O índice combina cobertura, domínio, retenção, consistência e simulados. Progresso real, melhora nesses fatores e evidência mais completa podem elevar o indicador; deterioração ou revisão insuficiente podem reduzi-lo. Fatores ausentes diminuem a confiança. O número não estima a chance de aprovação.'],action:{label:'Ver Índice de Prontidão',target:'overview'}},
    {id:'achievements',title:'Conquistas',summary:'Consistência, aprendizagem e decisões estratégicas.',paragraphs:['As conquistas reconhecem progresso, mas não alteram prioridades nem o Índice de Prontidão. Estrategista exige estudo em dez tópicos distintos de alto impacto; Cobertura crítica exige domínio com evidência suficiente nos tópicos críticos de uma disciplina; Prova mapeada exige quatro provas completas no concurso ativo. As conquistas bloqueadas mostram o que falta.'],action:{label:'Ver conquistas',target:'achievements'}},
    {id:'outcomes',title:'Histórico e resultados posteriores',summary:'Recomendação → execução → medição → auditoria.',paragraphs:['O histórico guarda a recomendação, a decisão e o resultado observado depois. Isso ajuda a avaliar a estratégia, mas uma melhora posterior não prova que a recomendação causou a melhora.'],action:{label:'Ver histórico',target:'history'}},
    {id:'report',title:'Relatório e PDF',summary:'Uma fotografia estratégica do período escolhido.',paragraphs:['O PDF resume planejamento, desempenho, recomendações, Inteligência da Prova e foco dos últimos sete dias do período. Inclui cobertura e confiança históricas e até três lacunas estratégicas. Use-o para revisar ou imprimir; ele não substitui o backup JSON.'],action:{label:'Ir ao relatório PDF',target:'report'}},
    {id:'projections',title:'Projeções e cenários',summary:'Faixas estimadas para apoiar a leitura da preparação.',paragraphs:['Projeções e cenários refletem os dados disponíveis e hipóteses de capacidade. São estimativas para comparar caminhos, não probabilidade de aprovação nem garantia de resultado.'],action:{label:'Ver projeções',target:'overview'}}
  ]},
  {id:'guide-exam',title:'Inteligência da prova',summary:'Histórico, incidência, qualidade e Matriz Prova × Você.',entries:[
    {id:'exam-history',title:'Provas históricas',summary:'Entenda o que costuma aparecer na prova.',flow:['Provas históricas','Questões classificadas','Tópicos e incidência','Confiança','Impacto na prova'],paragraphs:['Importe provas históricas em JSON com prévia e confirmação das associações. Essas questões formam evidência de incidência e ficam separadas das questões que você resolveu para medir seu desempenho. A reimportação da mesma prova evita duplicatas.'],action:{label:'Abrir Inteligência da Prova',target:'exam'}},
    {id:'exam-quality',title:'Qualidade do histórico',summary:'A força da amostra vem antes do impacto.',paragraphs:['O StudyTrack observa provas completas e parciais, cobertura conhecida, questões classificadas, pendências e confiança. Provas parciais não são tratadas como ausência do tópico. Uma base pequena não significa desempenho ruim: quando o histórico é insuficiente, sua influência no impacto é limitada.'],action:{label:'Revisar qualidade da base',target:'exam'}},
    {id:'exam-audit',title:'Configurado × Histórico',summary:'Compare sua estratégia com a evidência sem sobrescrever escolhas.',paragraphs:['A auditoria confronta o impacto configurado com o observado nas provas e destaca alinhamentos e divergências. Valores manuais ou oficiais continuam prevalecendo até você decidir alterá-los; inferência histórica nunca é apresentada como peso oficial.'],bullets:['Exemplo: configurado 80/100; histórico observado 84/100.','O estado pode ser alinhado, enquanto o valor usado segue a fonte configurada.'],action:{label:'Ver auditoria',target:'audit'}},
    {id:'exam-matrix',title:'Matriz Prova × Você',summary:'Importância da prova e situação pessoal lado a lado.',flow:['Prova: incidência e impacto','Você: domínio, retenção e tendência','Prioridade: importância × necessidade'],paragraphs:['Um tópico frequente que você domina pode pedir manutenção. Outro, também importante e com domínio baixo, pode merecer estudo agora. A matriz permite filtrar provas e abrir o detalhe de um tópico para entender essa combinação.'],bullets:['Exemplo: impacto alto e domínio 42/100 indicam uma lacuna relevante.'],action:{label:'Abrir Matriz Prova × Você',target:'matrix'}}
  ]},
  {id:'guide-safety',title:'Dados e segurança',summary:'Backup, uso offline, atalhos e demonstração.',entries:[
    {id:'backup',title:'Seus dados e backup',summary:'Os dados ficam neste navegador.',paragraphs:['O StudyTrack funciona com dados locais, sem conta obrigatória. Exporte backups JSON regularmente, sobretudo antes de limpar dados, trocar de navegador ou fazer mudanças importantes. A restauração valida o arquivo antes de substituir a base; o PDF não é restaurável. Depois do primeiro carregamento completo por HTTP, o PWA instalado pode abrir offline.'],action:{label:'Ir ao backup',target:'backup'}},
    {id:'guide-shortcuts',title:'Acesso rápido e atalhos',summary:'Encontre áreas, ações e tópicos pelo teclado.',paragraphs:['Ctrl + K (ou Cmd + K no Mac) abre a busca global de ações, páginas e tópicos. Ctrl/Cmd + Shift + 1–8 alterna entre as oito áreas. Esc fecha busca, menu ou modal. Com uma aba em foco, use setas, Home e End para navegar.']},
    {id:'demo',title:'Modo demonstração',summary:'Explore o produto com dados fictícios separados.',paragraphs:['A demonstração permite conhecer prioridades, planejamento, relatórios e histórico sem cadastrar uma base real. Reiniciar ou encerrar a demo não altera seus dados reais.'],action:{label:'Explorar demonstração',target:'demo'}}
  ]}
];

export const HELP_GLOSSARY=[
  ['Índice de Prontidão','Síntese de cobertura, domínio, retenção, consistência e simulados. Não é probabilidade de aprovação.'],
  ['Domínio','Estimativa do desempenho consolidado em um tópico, acompanhada da força da evidência.'],
  ['Retenção','Sinal de manutenção do conhecimento baseado no histórico disponível de estudo e revisão.'],
  ['Impacto','Importância estratégica do tópico para a prova; pode vir de configuração ou de histórico validado.'],
  ['Incidência','Presença de um tópico nas provas analisadas, distinta da participação em questões.'],
  ['Confiança','Quanto dado sustenta uma medida. Evidência limitada preserva a incerteza.'],
  ['Evidência','Sessões, questões, revisões e provas históricas usadas conforme a métrica calculada.'],
  ['Lacuna','Encontro entre relevância para a prova e necessidade pessoal de aprendizagem.'],
  ['Foco estratégico','Parcela do tempo registrado em tópicos de alto impacto; indicador sem meta mínima.'],
  ['Planejamento adaptativo','Proposta confirmável de redistribuir minutos dentro da capacidade semanal.']
];

export const HELP_FAQ=[
  ['Por que meu índice ainda tem baixa confiança?','Ainda há pouca evidência em um ou mais fatores. Baixa confiança não significa automaticamente baixo desempenho.'],
  ['Prontidão é probabilidade de aprovação?','Não. É um índice composto de acompanhamento, que deve ser lido junto às análises detalhadas.'],
  ['O que acontece se eu perder um dia do plano?','Registre o que foi feito, trate pendências em Hoje e confirme uma nova proposta se a carga deixar de ser viável.'],
  ['Como levo meus dados para outro dispositivo?','Exporte um backup JSON, transfira o arquivo com segurança e importe-o no outro navegador. O PDF não restaura dados.'],
  ['O aplicativo funciona sem internet?','Depois do primeiro carregamento completo por HTTP e da instalação, o PWA pode abrir offline; os registros continuam locais.']
];
