export function buildReplanProposal({plans=[],periodStart,periodEnd,futureDays=[]}={}){
  const inPeriod=plans.filter(plan=>plan.date>=periodStart&&plan.date<=periodEnd);
  const plannedMinutes=inPeriod.reduce((sum,plan)=>sum+(plan.items||[]).filter(item=>!['skipped','replaced'].includes(item.status)).reduce((n,item)=>n+(Number(item.plannedMinutes)||0),0),0);
  const executedMinutes=Math.round(inPeriod.reduce((sum,plan)=>sum+(plan.items||[]).reduce((n,item)=>n+(Number(item.executedSeconds)||0)/60,0),0));
  const pendingItems=inPeriod.flatMap(plan=>(plan.items||[]).filter(item=>!['completed','skipped','replaced','deferred'].includes(item.status)).map(item=>({sourcePlanId:plan.id,sourceItemId:item.id,subjectId:item.subjectId||null,topicId:item.topicId||null,remainingMinutes:Math.max(0,Math.round((Number(item.plannedMinutes)||0)-(Number(item.executedSeconds)||0)/60)),priority:Number(item.score)||0}))).filter(item=>item.remainingMinutes>0).sort((a,b)=>b.priority-a.priority);
  const deficitMinutes=pendingItems.reduce((sum,item)=>sum+item.remainingMinutes,0);
  const capacities=(futureDays||[]).map(day=>({date:day.date,remaining:Math.max(0,Math.round(Number(day.availableMinutes)||0))}));
  const allocations=[];let remaining=deficitMinutes;
  pendingItems.forEach(item=>{let itemRemaining=item.remainingMinutes;capacities.forEach(day=>{if(itemRemaining<=0||day.remaining<=0)return;const minutes=Math.min(itemRemaining,day.remaining);allocations.push({...item,date:day.date,minutes});itemRemaining-=minutes;day.remaining-=minutes;remaining-=minutes})});
  const redistributedMinutes=allocations.reduce((sum,item)=>sum+item.minutes,0);
  return {state:deficitMinutes?'proposal':'balanced',periodStart,periodEnd,plannedMinutes,executedMinutes,deficitMinutes,redistributedMinutes,discardedMinutes:Math.max(0,remaining),pendingItems,allocations,reasons:deficitMinutes?['execução abaixo do planejado no período']:[]};
}

export function applyReplan({dailyPlans=[],proposal,operationId,now,idGenerator}={}){
  if(proposal?.state!=='proposal'||!operationId||typeof idGenerator!=='function')return {changes:[],createdItems:0};
  const changes=[],originalStatuses=new Map();
  for(const allocation of proposal.allocations){const sourcePlan=dailyPlans.find(plan=>plan.id===allocation.sourcePlanId),sourceItem=sourcePlan?.items?.find(item=>item.id===allocation.sourceItemId);if(!sourceItem)continue;if(dailyPlans.some(plan=>(plan.items||[]).some(item=>item.rescheduleOperationId===operationId&&item.rescheduledFromId===sourceItem.id&&item.currentDate===allocation.date)))continue;let destination=dailyPlans.find(plan=>plan.date===allocation.date);if(!destination){destination={id:idGenerator('plan'),date:allocation.date,availableMinutes:allocation.minutes,plannedMinutes:0,flexMinutes:0,createdAt:now,updatedAt:now,items:[]};dailyPlans.push(destination)}const sourceKey=`${sourcePlan.id}:${sourceItem.id}`;if(!originalStatuses.has(sourceKey))originalStatuses.set(sourceKey,sourceItem.status);sourceItem.status='deferred';sourceItem.skippedReason=`Redistribuída para ${allocation.date}`;sourcePlan.updatedAt=now;const created={...sourceItem,id:idGenerator('plan-item'),plannedMinutes:allocation.minutes,executedSeconds:0,status:'planned',sessionIds:[],originalDate:sourceItem.originalDate||sourcePlan.date,currentDate:allocation.date,rescheduleCount:(Number(sourceItem.rescheduleCount)||0)+1,skippedReason:null,rescheduledFromId:sourceItem.id,rescheduleOperationId:operationId,createdAt:now,lastExecutedAt:null};destination.items.push(created);destination.plannedMinutes=(destination.items||[]).filter(item=>!['skipped','replaced'].includes(item.status)).reduce((sum,item)=>sum+(Number(item.plannedMinutes)||0),0);destination.flexMinutes=Math.max(0,(Number(destination.availableMinutes)||0)-destination.plannedMinutes);destination.updatedAt=now;changes.push({sourcePlanId:sourcePlan.id,sourceItemId:sourceItem.id,sourcePreviousStatus:originalStatuses.get(sourceKey),destinationPlanId:destination.id,destinationItemId:created.id,date:allocation.date,minutes:allocation.minutes})}
  return {changes,createdItems:changes.length,operationId};
}

export function undoReplan({dailyPlans=[],adjustment}={}){
  const protectedItems=[],undoneChanges=[],protectedSources=new Set(),sourceKey=change=>`${change.sourcePlanId}:${change.sourceItemId}`;
  for(const change of adjustment?.changes||[]){const destination=dailyPlans.find(plan=>plan.id===change.destinationPlanId),item=destination?.items?.find(candidate=>candidate.id===change.destinationItemId);if(!item)continue;const executed=Number(item.executedSeconds)>0||(item.sessionIds||[]).length>0||['in_progress','partial','completed'].includes(item.status);if(executed){protectedItems.push(item.id);protectedSources.add(sourceKey(change));continue}destination.items=destination.items.filter(candidate=>candidate.id!==item.id);destination.plannedMinutes=destination.items.filter(candidate=>!['skipped','replaced'].includes(candidate.status)).reduce((sum,candidate)=>sum+(Number(candidate.plannedMinutes)||0),0);destination.flexMinutes=Math.max(0,(Number(destination.availableMinutes)||0)-destination.plannedMinutes);undoneChanges.push(change)}
  undoneChanges.filter(change=>!protectedSources.has(sourceKey(change))).forEach(change=>{const source=dailyPlans.find(plan=>plan.id===change.sourcePlanId)?.items?.find(candidate=>candidate.id===change.sourceItemId);if(source){source.status=change.sourcePreviousStatus||'planned';source.skippedReason=null}});
  for(let index=dailyPlans.length-1;index>=0;index--)if(!dailyPlans[index].items?.length)dailyPlans.splice(index,1);
  return {undoneChanges,protectedItems,complete:protectedItems.length===0};
}
