import test from 'node:test';import assert from 'node:assert/strict';
import {previewExamStructureImport,createExamImportService} from '../../src/application/subjects/exam-import-service.js';
import {createSubjectService} from '../../src/application/subjects/subject-service.js';import {createSubjectsRepository} from '../../src/repositories/subjects-repository.js';
const preset={id:'p',subjects:[{id:'s1',name:'Matemática',topics:[{id:'t1',name:'Porcentagem'},{id:'t2',name:'Juros'}]}]};
function fixture(subjects=[]){const state={subjects},repository=createSubjectsRepository({getState:()=>state});let id=0;const subjectService=createSubjectService({repository,clock:{nowISO:()=> '2026-09-07T12:00:00Z'},idGenerator:type=>`${type}-${++id}`});return{state,service:createExamImportService({subjectService,getSubjects:()=>state.subjects})}}
test('preview compara nomes ignorando acentos, caixa e espaços',()=>{const result=previewExamStructureImport({preset,subjects:[{id:'old',name:' matematica ',topics:[{id:'x',name:'PORCENTÁGEM'}]}]});assert.deepEqual([result.addedSubjects,result.existingSubjects,result.addedTopics,result.existingTopics],[0,1,1,1])});
test('merge preserva ids e não duplica em importações repetidas',()=>{const{state,service}=fixture([{id:'old',name:'Matemática',topics:[]}]);let result=service.importExamStructure({preset});assert.equal(result.addedTopics,2);assert.equal(state.subjects[0].id,'old');service.importExamStructure({preset});assert.equal(state.subjects.length,1);assert.equal(state.subjects[0].topics.length,2)});
test('seleção parcial importa somente os tópicos escolhidos',()=>{const{state,service}=fixture();service.importExamStructure({preset,selectedSubjectIds:new Set(['s1']),selectedTopicIds:new Set(['s1:t2'])});assert.deepEqual(state.subjects[0].topics.map(item=>item.name),['Juros'])});
test('catálogo grande permanece rápido e idempotente',()=>{const large={subjects:Array.from({length:10},(_,s)=>({id:`s${s}`,name:`Disciplina ${s}`,topics:Array.from({length:25},(_,t)=>({id:`t${t}`,name:`Tópico ${t}`}))}))};const{state,service}=fixture(),started=performance.now();service.importExamStructure({preset:large});service.importExamStructure({preset:large});assert.equal(state.subjects.length,10);assert.equal(state.subjects.reduce((sum,item)=>sum+item.topics.length,0),250);assert.ok(performance.now()-started<1000)});
