import test from 'node:test';
import assert from 'node:assert/strict';
import {HELP_CATEGORIES} from '../../src/ui/help/help-content.js';
import {renderHelpCenter} from '../../src/ui/help/help-renderer.js';
test('ajuda preserva IDs únicos e oferece sete categorias com estrutura de busca',()=>{assert.deepEqual(HELP_CATEGORIES.map(category=>category.title),['Comece por aqui','Estudar','Planejar','Analisar','Prova','Metas','Dados']);const ids=HELP_CATEGORIES.flatMap(category=>[category.id,...category.entries.map(entry=>entry.id)]);assert.equal(new Set(ids).size,ids.length);for(const entry of HELP_CATEGORIES.flatMap(category=>category.entries)){assert.ok(Array.isArray(entry.keywords));assert.ok(Array.isArray(entry.concepts));assert.ok(Array.isArray(entry.questions))}});
test('renderer mantém busca, ações e cards de leitura direta',()=>{const html=renderHelpCenter();assert.equal((html.match(/data-help-category=/g)||[]).length,7);assert.match(html,/instruction-card-grid/);assert.match(html,/id="helpSearch"/);assert.match(html,/data-help-action="today"/);assert.doesNotMatch(html,/<details/)});
test('metadados e conteúdo são escapados na renderização',()=>{const html=renderHelpCenter({categories:[{id:'safe',title:'Teste',summary:'',entries:[{id:'one',title:'<script>',summary:'',keywords:['" onmouseover="bad'],paragraphs:['<img>']}]}]});assert.match(html,/&lt;script&gt;/);assert.match(html,/&quot; onmouseover=&quot;bad/);assert.doesNotMatch(html,/<img>/)});

import {renderHelpVisual} from '../../src/ui/help/help-visuals.js';
test('mapa semântico mantém seis etapas em ordem e primeiros passos sem accordion',()=>{const category=HELP_CATEGORIES.find(category=>category.id==='guide-start'),map=category.entries.find(entry=>entry.id==='how-it-works');assert.deepEqual(map.visual.steps.map(step=>step.title),['Configurar','Planejar','Estudar','Registrar','Analisar','Ajustar']);assert.equal(category.entries.find(entry=>entry.id==='first-steps').steps.length,6);const html=renderHelpVisual(map.visual);assert.match(html,/<ol class="instruction-flow">/);assert.equal((html.match(/<li>/g)||[]).length,6)});
test('exemplos são identificados e não executam ações reais',()=>{const html=renderHelpVisual({type:'action',title:'Atividade',subject:'<img>',topic:'Texto',activity:'Teoria',minutes:35});assert.match(html,/Exemplo ilustrativo/);assert.match(html,/&lt;img&gt;/);assert.doesNotMatch(html,/<button|data-help-action/);assert.equal(renderHelpVisual({type:'unknown'}),'')});
test('exemplo de progresso distingue minutos e atividades concluídas',()=>{const today=HELP_CATEGORIES.find(category=>category.id==='guide-areas').entries.find(entry=>entry.id==='today-guide');const html=renderHelpVisual(today.visual);assert.match(html,/35 min/);assert.match(html,/20 min/);assert.match(html,/57% de progresso/);assert.match(html,/0 de 1 atividade concluída/)});
