import test from 'node:test';import assert from 'node:assert/strict';
import {createPlanningRepository} from '../../src/repositories/planning-repository.js';
import {createStudyPlanService} from '../../src/application/planning/study-plan-service.js';
import {createDailyPlanService} from '../../src/application/planning/daily-plan-service.js';
import {createReplanService} from '../../src/application/planning/replan-service.js';

const clock={nowISO:()=> '2026-09-02T12:00:00.000Z'};let sequence=0;const id=prefix=>`${prefix}-${++sequence}`;
test('confirma plano estratégico com vínculos estáveis',()=>{sequence=0;const state={studyPlans:[],dailyPlans:[],planAdjustments:[]},repository=createPlanningRepository({getState:()=>state}),service=createStudyPlanService({repository,calculate:value=>value,clock,idGenerator:id,algorithmVersion:()=>3});const plan=service.confirm({state:'ready',items:[{id:'topic-1',minutes:30}]});assert.equal(plan.items[0].studyPlanId,plan.id);assert.equal(service.getActive().algorithmVersion,3)});
test('serviço diário registra operação e preserva desfazer',()=>{sequence=0;const state={studyPlans:[{id:'s1',dailyPlanOperations:[]}],dailyPlans:[],planAdjustments:[]},repository=createPlanningRepository({getState:()=>state}),service=createDailyPlanService({repository,clock,idGenerator:id,buildProposal:x=>x,applyProposal:({dailyPlans,operationId})=>{dailyPlans.push({id:'d1',items:[]});return{createdItems:1,operationId}},undoGeneration:()=>({complete:true,protectedItems:[],removedItems:1})});const result=service.confirm({state:'proposal'},state.studyPlans[0]);assert.equal(result.createdItems,1);assert.equal(state.studyPlans[0].dailyPlanOperations.length,1);service.undo(state.studyPlans[0].dailyPlanOperations[0],state.studyPlans[0]);assert.ok(state.studyPlans[0].dailyPlanOperations[0].undoneAt)});
test('replanejamento salva ajuste auditável e permite desfazer',()=>{sequence=0;const state={studyPlans:[],dailyPlans:[],planAdjustments:[]},repository=createPlanningRepository({getState:()=>state}),service=createReplanService({repository,clock,idGenerator:id,buildProposal:x=>x,applyProposal:({operationId})=>({changes:[{id:'c1'}],createdItems:1,operationId}),undoProposal:()=>({complete:true,protectedItems:[]})});const applied=service.confirm({state:'proposal',allocations:[]});assert.equal(repository.findAdjustment(applied.adjustment.id).operationId,applied.adjustment.operationId);assert.equal(service.undo(applied.adjustment.id).complete,true)});
