import test from 'node:test';import assert from 'node:assert/strict';
import {captureRecommendationBaseline,captureRecommendationSnapshot,measureRecommendationOutcome,recommendationOutcomeConfidence} from '../../src/application/recommendations/outcome-service.js';
import {evaluateRecommendationOutcome} from '../../src/domain/recommendations/recommendation-outcome.js';

test('registra uma linha de base analítica normalizada',()=>{assert.deepEqual(captureRecommendationBaseline({mastery:51,accuracy:58,questionVolume:32,retentionScore:44,reviewHealth:39,risk:72,daysSinceContact:7,measuredAt:'2026-09-01T10:00:00Z'}),{mastery:51,retention:44,reviewHealth:39,accuracy:58,risk:72,retentionScore:44,questionVolume:32,daysSinceContact:7,trend:null,measuredAt:'2026-09-01T10:00:00Z'})});
test('preserva snapshot imutável da recomendação',()=>{const recommendation={recommendationId:'r1',algorithmVersion:3,subjectId:'s1',topicId:'t1',score:87,risk:{value:71},estimatedMinutes:40,recommendedQuestions:20,shownAt:'2026-09-01T10:00:00Z'},baseline=captureRecommendationBaseline({mastery:50});const snapshot=captureRecommendationSnapshot(recommendation,{baseline});baseline.mastery=99;assert.equal(snapshot.before.mastery,50);assert.equal(snapshot.priorityScore,87);assert.equal(snapshot.riskScore,71)});
test('classifica a confiança pelo volume posterior',()=>{assert.equal(recommendationOutcomeConfidence(0),'Aguardando');assert.equal(recommendationOutcomeConfidence(12),'Amostra inicial');assert.equal(recommendationOutcomeConfidence(32),'Estimativa');assert.equal(recommendationOutcomeConfidence(50),'Mais confiável')});
test('não atribui impacto com amostra pequena ou muitas intervenções',()=>{const feedback={baseline:{accuracy:55,retention:50}};const outcome=measureRecommendationOutcome(feedback,{accuracyAfter:71,questionVolumeAfter:12,retentionAfter:60,measuredAt:'2026-09-02T10:00:00Z',daysElapsed:2,otherActivities:4});assert.equal(outcome.attributionEligible,false);assert.ok(outcome.reasons.length>=2);assert.equal(feedback.outcome,outcome)});
test('aceita avaliação com amostra e janela suficientes sem alterar pesos',()=>{const feedback={algorithmVersion:3,baseline:{accuracy:55,retention:50}};const outcome=measureRecommendationOutcome(feedback,{accuracyAfter:71,questionVolumeAfter:52,nextReviewRating:'Bom',retentionAfter:68,measuredAt:'2026-09-08T10:00:00Z',daysElapsed:7,otherActivities:1});assert.equal(outcome.confidenceLabel,'Mais confiável');assert.equal(outcome.attributionEligible,true);assert.equal(feedback.algorithmVersion,3)});
test('classifica melhora usando deltas positivos e inversão do risco',()=>{const outcome=evaluateRecommendationOutcome({before:{mastery:50,retention:45,accuracy:55,risk:80},after:{mastery:62,retention:55,accuracy:66,risk:64},questionVolume:40,daysElapsed:5});assert.equal(outcome.state,'positive');assert.equal(outcome.delta.risk,16);assert.ok(outcome.averageDelta>3);assert.equal(outcome.attributionEligible,true)});
test('mantém resultado pendente antes da janela mínima',()=>{const outcome=evaluateRecommendationOutcome({before:{mastery:50,accuracy:55},after:{mastery:60,accuracy:65},questionVolume:30,daysElapsed:0});assert.equal(outcome.state,'pending');assert.equal(outcome.attributionEligible,false)});
